// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RAG.Infrastructure.Data;

#nullable disable

namespace RAG.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205003605_AddSeedDatasetsTable")]
    partial class AddSeedDatasetsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RAG.Core.Domain.AccessAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("PermissionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("permission_type");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("idx_access_audit_actor");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_access_audit_document");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_access_audit_timestamp");

                    b.ToTable("access_audit_log", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_audit_logs_action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_audit_logs_user");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chunk_ids");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Source")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_documents_owner_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_documents_tenant_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_documents_title");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.DocumentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("permission_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_document_access_document");

                    b.HasIndex("Permission")
                        .HasDatabaseName("idx_document_access_permission");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_document_access_user");

                    b.HasIndex("DocumentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_document_access_unique");

                    b.ToTable("document_access", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("EndIndex")
                        .HasColumnType("integer")
                        .HasColumnName("end_index");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("StartIndex")
                        .HasColumnType("integer")
                        .HasColumnName("start_index");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunks_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_chunks_tenant_id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .HasDatabaseName("idx_chunks_document_chunk");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.DocumentHash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_document_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_tenant_id");

                    b.HasIndex("Hash", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("idx_hash_tenant");

                    b.ToTable("document_hashes", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_evaluations_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_evaluations_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_evaluations_name_unique");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_evaluations_type");

                    b.ToTable("evaluations", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.EvaluationMetricRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("metric_name");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("numeric")
                        .HasColumnName("metric_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SampleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sample_id");

                    b.HasKey("Id");

                    b.HasIndex("MetricName")
                        .HasDatabaseName("idx_eval_metrics_name");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_eval_metrics_recorded");

                    b.HasIndex("RunId")
                        .HasDatabaseName("idx_eval_metrics_run");

                    b.HasIndex("RunId", "MetricName")
                        .HasDatabaseName("idx_eval_metrics_run_name");

                    b.ToTable("evaluation_metrics", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.EvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedQueries")
                        .HasColumnType("integer")
                        .HasColumnName("completed_queries");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<int>("FailedQueries")
                        .HasColumnType("integer")
                        .HasColumnName("failed_queries");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InitiatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("ResultsSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("results_summary");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalQueries")
                        .HasColumnType("integer")
                        .HasColumnName("total_queries");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .HasDatabaseName("idx_eval_runs_evaluation");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_eval_runs_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_eval_runs_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_eval_runs_tenant");

                    b.ToTable("evaluation_runs", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.IndexRebuildJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("EstimatedDocuments")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_documents");

                    b.Property<bool>("IncludeEmbeddings")
                        .HasColumnType("boolean")
                        .HasColumnName("include_embeddings");

                    b.Property<Guid?>("InitiatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by");

                    b.Property<int>("ProcessedDocuments")
                        .HasColumnType("integer")
                        .HasColumnName("processed_documents");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("JobId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_rebuild_jobs_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_rebuild_jobs_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_rebuild_jobs_tenant");

                    b.ToTable("index_rebuild_jobs", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.SeedDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DocumentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("documents_count");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTime>("LoadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("LoadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("loaded_by");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("QueriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("queries_count");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("idx_seed_datasets_hash");

                    b.HasIndex("LoadedAt")
                        .HasDatabaseName("idx_seed_datasets_loaded_at");

                    b.HasIndex("LoadedBy")
                        .HasDatabaseName("idx_seed_datasets_loaded_by");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_seed_datasets_name_unique");

                    b.ToTable("seed_datasets", (string)null);
                });

            modelBuilder.Entity("RAG.Core.Domain.DocumentAccess", b =>
                {
                    b.HasOne("RAG.Core.Domain.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RAG.Core.Domain.EvaluationMetricRecord", b =>
                {
                    b.HasOne("RAG.Core.Domain.EvaluationRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });
#pragma warning restore 612, 618
        }
    }
}
